# frozen_string_literal: true

require "rails_helper"

# Guarda contra un problema real y silencioso: la extensión VSCode "Ruby LSP"
# a veces reescribe bin/rails apuntándolo a su propio Gemfile temporal
# (.ruby-lsp/Gemfile), que está en .gitignore y no existe fuera de la máquina
# del developer — ni en CI ni en el contenedor de producción. Si eso llega a
# commitearse, el binstub no falla ruidosamente: en algunos casos imprime la
# ayuda de `rails` y sale con éxito (exit 0) sin ejecutar nada. Ver
# CLAVISCO-PLATFORM-STANDARDS.md Sección 11 para el detalle completo.
RSpec.describe "Binstubs" do
  it "bin/rails es el binstub de Rails, no el de Bundler" do
    content = File.read(Rails.root.join("bin/rails"))

    expect(content).not_to include("This file was generated by Bundler"),
      "bin/rails es el binstub de Bundler (probablemente regenerado por la " \
      "extensión Ruby LSP). Restaure el binstub de Rails: debe definir " \
      "APP_PATH y requerir config/boot."
    expect(content).to include("APP_PATH")
  end

  it "ningún binstub apunta su BUNDLE_GEMFILE a .ruby-lsp/Gemfile" do
    rotos = Dir[Rails.root.join("bin/*")].select do |path|
      File.file?(path) && File.read(path) =~ /ENV\["BUNDLE_GEMFILE"\].*\.ruby-lsp/
    end

    expect(rotos).to be_empty,
      "Estos binstubs apuntan su BUNDLE_GEMFILE a .ruby-lsp/Gemfile, que no " \
      "existe fuera de la máquina del developer: #{rotos.join(', ')}. Corrija " \
      "reemplazando '../.ruby-lsp/Gemfile' por '../Gemfile' en cada uno."
  end
end
